# Target Path: ...\Toolkit_Files\SendAlert.ps1
param (
    [string]$ScriptName,
    [string]$ErrorMessage,
    [string]$ErrorLog = "$env:USERPROFILE\Desktop\IT_Toolkit_Logs\Toolkit_Errors.txt",
    [string]$SmtpServer,
    [int]$SmtpPort
)

. "$PSScriptRoot\ToolkitCommon.ps1"
$Config = Get-ToolkitConfig
if ([string]::IsNullOrWhiteSpace($SmtpServer)) { $SmtpServer = $Config.SmtpServer }
if (-not $SmtpPort) { $SmtpPort = $Config.SmtpPort }
Invoke-LogRotation -LogPath $ErrorLog -MaxBytes $Config.LogRotateMaxBytes -KeepCount $Config.LogRotateKeep

$ConfigPath = "$PSScriptRoot\MailConfig.xml"
$AdminEmailPath = "$PSScriptRoot\MailConfig.AdminEmail.txt"

if (-not (Test-Path $ConfigPath) -or -not (Test-Path $AdminEmailPath)) {
    # Alert engine not configured yet (run ConfigureEmail.ps1 first) — log and bail quietly.
    "[$(Get-Date)] [Email Alert Engine] Skipped: MailConfig.xml or AdminEmail.txt missing. Run ConfigureEmail.ps1 first." | Out-File $ErrorLog -Append
    return
}

# Securely import and auto-decrypt the credential block using DPAPI.
# NOTE: this only works if the CURRENT account matches the account that ran ConfigureEmail.ps1.
try {
    $Credential = Import-Clixml -Path $ConfigPath
} catch {
    "[$(Get-Date)] [Email Alert Engine] Failed to decrypt MailConfig.xml under the current account ($env:USERNAME). Re-run ConfigureEmail.ps1 as this account. Detail: $_" | Out-File $ErrorLog -Append
    return
}

$MailTo = (Get-Content -Path $AdminEmailPath -Raw).Trim()
$MailFrom = $Credential.UserName   # <-- Dynamically pulls your login address

$Body = @"
<h2>IT Toolkit - Critical Execution Exception Alert</h2>
<p><strong>Timestamp:</strong> $(Get-Date)</p>
<p><strong>System Name:</strong> $env:COMPUTERNAME</p>
<p><strong>Trigger Module:</strong> $ScriptName</p>
<hr />
<p style="color:red; font-family:monospace; background-color:#f8f9fa; padding:10px; border:1px solid #ddd;">
    $ErrorMessage
</p>
<hr />
<p><em>This is an automated notification generated by the PCantu IT Administration Toolkit Suite.</em></p>
"@

$MailParams = @{
    From       = $MailFrom
    To         = $MailTo
    Subject    = "ALERT: IT Toolkit Script Exception on $env:COMPUTERNAME"
    Body       = $Body
    BodyAsHtml = $true
    SmtpServer = $SmtpServer
    Port       = $SmtpPort
    Credential = $Credential
    UseSsl     = $true
}

try {
    Send-MailMessage @MailParams -ErrorAction Stop
} catch {
    "[$(Get-Date)] [Email Alert Engine] Failed to dispatch alert: $_" | Out-File $ErrorLog -Append
}
